# Generated by Django 2.1.4 on 2018-12-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='member',
            new_name='member',
        ),
    ]
