# Generated by Django 2.1.4 on 2018-12-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_api', '0003_auto_20181212_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='test1',
            new_name='test12',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='test2',
            new_name='test23',
        ),
    ]
